# Generated by Django 2.2 on 2019-12-13 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_players', models.IntegerField(default=100)),
                ('num_werewolves', models.IntegerField(default=0)),
                ('has_village_idiot', models.BooleanField(default=False)),
                ('has_cupid', models.BooleanField(default=False)),
                ('has_lovers', models.BooleanField(default=False)),
                ('has_twins', models.BooleanField(default=False)),
                ('has_accursed_one', models.BooleanField(default=False)),
                ('has_seer', models.BooleanField(default=False)),
                ('has_witch', models.BooleanField(default=False)),
                ('has_defender', models.BooleanField(default=False)),
                ('has_hunter', models.BooleanField(default=False)),
                ('has_wild_child', models.BooleanField(default=False)),
                ('has_role_model', models.BooleanField(default=False)),
                ('has_little_child', models.BooleanField(default=False)),
                ('has_rusty_knight', models.BooleanField(default=False)),
                ('has_elder', models.BooleanField(default=False)),
                ('has_angel', models.BooleanField(default=False)),
                ('has_gypsy', models.BooleanField(default=False)),
                ('allow_spectators', models.BooleanField(default=False)),
                ('started', models.BooleanField(default=False)),
                ('ended', models.BooleanField(default=False)),
                ('current_phase', models.CharField(default='Lobby', max_length=45)),
                ('current_turn', models.IntegerField(default=0)),
                ('winning_team', models.CharField(max_length=45, null=True)),
                ('join_key', models.CharField(max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_hosted', to='login_app.User')),
                ('players', models.ManyToManyField(related_name='games_joined', to='login_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAlive', models.BooleanField(default=True)),
                ('isBanned', models.BooleanField(default=False)),
                ('turn_died', models.IntegerField(null=True)),
                ('role_notes', models.CharField(max_length=255, null=True)),
                ('primary_ammo', models.IntegerField(default=0)),
                ('secondary_ammo', models.IntegerField(default=0)),
                ('successes', models.IntegerField(default=0)),
                ('isActivePlayer', models.BooleanField(default=True)),
                ('role_name', models.CharField(max_length=45, null=True)),
                ('secondary_role_name', models.CharField(max_length=45, null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='werewolf_app.Game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='login_app.User')),
            ],
        ),
    ]
