# Generated by Django 2.2 on 2019-12-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='allow_spectators',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='has_accursed_one',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='has_cupid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='has_defender',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='has_lovers',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='has_seer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='has_witch',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='num_werewolves',
            field=models.IntegerField(default=2),
        ),
    ]
