# Generated by Django 2.2 on 2019-12-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf_app', '0002_auto_20191213_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='isRoleModel',
            field=models.BooleanField(default=False),
        ),
    ]
