# Generated by Django 2.2 on 2019-12-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('werewolf_app', '0005_game_winning_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='losing_players',
            field=models.ManyToManyField(related_name='games_lost', to='login_app.User'),
        ),
    ]
