# Generated by Django 2.2 on 2019-12-18 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf_app', '0006_game_losing_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField(default=0)),
                ('phase', models.CharField(max_length=1000, null=True)),
                ('wwTarget', models.CharField(default='There is currently nothing stored in wwTarget', max_length=1000)),
                ('prevWwTarget', models.CharField(default='There is currently nothing stored in prevWwTarget', max_length=1000)),
                ('target_switched', models.BooleanField(default=False)),
                ('witchUsedPotion', models.BooleanField(default=False)),
                ('witchUsedPoison', models.BooleanField(default=False)),
                ('littleChildCaught', models.BooleanField(default=False)),
                ('tetanus_infected', models.BooleanField(default=False)),
                ('hunter_killed', models.BooleanField(default=False)),
                ('lover_killed', models.BooleanField(default=False)),
                ('elder_saved', models.BooleanField(default=False)),
                ('role_model_killed', models.BooleanField(default=False)),
                ('seer_target', models.CharField(default='There is currently nothing stored in seer', max_length=1000)),
                ('hunter_target', models.CharField(default='There is currently nothing stored in hunter_target', max_length=1000)),
                ('def_target', models.CharField(default='There is currently nothing stored in def-target', max_length=1000)),
                ('tetanus_target', models.CharField(default='There is currently nothing stored in tetanus_target', max_length=1000)),
                ('poison_target', models.CharField(default='There is currently nothing stored in phase poison_target', max_length=1000)),
                ('ww_alive', models.IntegerField(null=True)),
                ('v_alive', models.IntegerField(null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnPhases', to='werewolf_app.Game')),
            ],
        ),
    ]
