# Generated by Django 2.2 on 2019-12-18 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf_app', '0007_turnphase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turnphase',
            old_name='prevWwTarget',
            new_name='wwNewTarget',
        ),
    ]
