# Generated by Django 2.2 on 2019-12-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf_app', '0009_turnphase_tetanus_killed'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnphase',
            name='vilNewTarget',
            field=models.CharField(default='There is currently nothing stored in vilNewTarget', max_length=1000),
        ),
        migrations.AddField(
            model_name='turnphase',
            name='vilTarget',
            field=models.CharField(default='There is currently nothing stored in vilTarget', max_length=1000),
        ),
        migrations.AlterField(
            model_name='turnphase',
            name='wwNewTarget',
            field=models.CharField(default='There is currently nothing stored in wwNewTarget', max_length=1000),
        ),
    ]
