# Generated by Django 2.2 on 2019-12-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf_app', '0011_turnphase_elder_voted_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnphase',
            name='village_idiot_voted_off',
            field=models.BooleanField(default=False),
        ),
    ]
