# Generated by Django 2.2 on 2019-12-19 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('werewolf_app', '0012_turnphase_village_idiot_voted_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='turnPhaseKilled',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players_killed', to='werewolf_app.TurnPhase'),
        ),
    ]
